name: Convertir PDF a HTML

on:
  push:
    paths:
      - '**/*.pdf'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Actualizar e instalar dependencias
      run: |
        sudo apt-get update
        sudo apt install -y libfontconfig1 libcairo2 libjpeg-turbo8 poppler-data

    - name: Descargar pdf2htmlEX
      run: |
        wget https://github.com/pdf2htmlEX/pdf2htmlEX/releases/download/v0.18.8.rc1/pdf2htmlEX-0.18.8.rc1-master-20200630-Ubuntu-focal-x86_64.deb
        sudo mv pdf2htmlEX-0.18.8.rc1-master-20200630-Ubuntu-focal-x86_64.deb pdf2htmlEX.deb

    - name: Instalar pdf2htmlEX
      run: |
        sudo apt install ./pdf2htmlEX.deb
        pdf2htmlEX -v

    - name: Convertir PDF en HTML
      run: |
        cd "$GITHUB_WORKSPACE"
        echo "Current directory: $(pwd)"
        for file in $(find . -type f -name '*.pdf' -not -path '*/\.*'); do
          if [[ "$file" == *.pdf ]]; then
            abs_path=$(realpath "$file")
            echo "Processing PDF file: $abs_path"
            html_file="$(dirname "$abs_path")/$(basename "$abs_path" .pdf).html"
            echo "Checking if HTML file exists: $html_file"
            if [ ! -f "$html_file" ]; then
              echo "Converting PDF to HTML..."
              cd "$(dirname "$abs_path")"
              pdf2htmlEX --zoom 1.3 "$(basename "$abs_path")"
              cd "$GITHUB_WORKSPACE"
            else
              echo "HTML file already exists. Skipping conversion."
            fi
          fi
        done

    - name: Crear Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: 'Convertir PDF a HTML'
        branch: 'convertir-pdf-a-html'
        title: 'Convertir PDF a HTML'
        body: 'Convertir todos los PDF en HTML'
